services:
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.envs/.local/.db.env
    ports:
      - "5433:5432"

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - migrations_accounts:/app/apps/accounts/migrations
      - migrations_tech:/app/apps/tech/migrations
      - migrations_repairs:/app/apps/repairs/migrations
    ports:
      - "8001:8000"
    env_file:
      - ./.envs/.local/.server.env
      - ./.envs/.local/.db.env
    command: >
      bash -c "uvicorn conf.asgi:application --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "5174:3000"
    env_file:
      - ./.envs/.local/.client.env
    volumes:
      - ./frontend:/code
      - nextjs_cache:/code/.next
      - turbo_cache:/code/.turbo
      - node_modules_cache:/code/node_modules/.cache
    depends_on:
      - backend
    command: sh -c "npm i && npm run dev"

volumes:
  postgres_data:
  migrations_accounts:
  migrations_tech:
  migrations_repairs:
  nextjs_cache:
  turbo_cache:
  node_modules_cache:
