services:
  db:
    image: postgres:16-alpine
    container_name: delivery-app-db
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.envs/.production/.db.env
    networks:
      - app-network
      - nginx-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  tek-mag:
    build: ./backend
    dockerfile: prod.dockerfile
    container_name: tek-mag
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - migrations_accounts:/app/apps/accounts/migrations
      - migrations_tech:/app/apps/tech/migrations
      - migrations_repairs:/app/apps/repairs/migrations
    ports:
      - "8001:8000"
    env_file:
      - ./.envs/.production/.server.env
      - ./.envs/.production/.db.env
    command: >
      bash -c "uvicorn conf.asgi:application --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - db
    networks:
      - app-network
      - nginx-network

  frontend:
    build:
      context: ./frontend
      dockerfile: prod.dockerfile
    container_name: tek-mag-frontend
    env_file:
      - ./.envs/.production/.client.env
    command: >
      sh -c "npm i && npx vite build --outDir /code/dist"
    volumes:
      - frontend_dist:/code/dist
    networks:
      - nginx-network

  volumes:
    postgres_data:
    migrations_accounts:
    migrations_tech:
    migrations_repairs:
    frontend_dist:

  networks:
    app-network:
      driver: bridge
      internal: true
    nginx-network:
      driver: bridge
      external: true
